#!/usr/bin/env bash
# information about the holbertonschool file
for a in {1..100}
do
	if [ $((a % 15)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((a % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((a % 3)) -eq 0 ]
	then
		echo "Fizz"
	else
		echo "$a"
	fi
done
