#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
x=0
while [ $x -le 9 ]
do
	x=$((x + 1))
	if [ $x == 4 ]
	then
		echo "bad luck"
	elif [ $x == 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
done
