#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
x=0
while [ $x -le 19 ]
do
	x=$((x + 1))
	echo $x
	case $x in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
done
